### ISSUE TITLE
Contradicting assignment of access way "download-cuf" to variables

### ISSUE THREAD

**Issue by rreitmann** [dzhw/gra2005-metadata#1]
The [bachelor data set](https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=data_sets&study=stu-gra2005$) are tagged without access way "download-cuf" however [the variables in those data sets](https://metadata.fdz.dzhw.eu/#!/de/search?page=1&type=variables&data-set=dat-gra2005-ds3$&study=stu-gra2005$) are tagged with access way "download cuf".

**Comment by rreitmann** [comment]
Somehow there is no private "gra2005" github repository only this one.

**Comment by fbaillet** [comment]
@anneweber könntest du diese Änderung übernehmen?

**Comment by anneweber** [comment]
@fbaillet Ja, ich mach mir ein Fähnchen dran. Ich fänd's nur super, wenn wir in diesem Zusammenhang noch einmal die Zuständigkeiten klären könnten in dem Planungstreffen für den Dauerbetrieb --> fällt sowas in den Arbeitsbereich des Release Managers oder nicht?

**Comment by fbaillet** [comment]
@anneweber ich weiß auch nicht so genau, am besten ihr besprecht das einfach mal bei der Dauerbetriebsplanung

**Comment by anneweber** [comment]
@rbirkelbach Könntest Du mir Bescheid geben, wenn der Datensatzreport für die Absolventen 2005 neu hochgeladen werden soll bzw. das damit zusammenhängende Neu-Release ansteht? Dann könnte man in diesem Zuge einfach noch die oben angegebene noch ausstehende Korrektur vornehmen. Wir können uns dazu am besten noch mal absprechen. Lieben Dank!

**Comment by rbirkelbach** [comment]
@anneweber Der wird neu generiert wenn die neue MDM-Version hochgeladen wird. Ich bin gerade dabei den Feinschliff für den Variablenreport zu machen.

**Comment by anneweber** [comment]
@rbirkelbach Alles klar, danke für die Info - lass uns am besten morgen noch mal kurz quatschen. Es müssten auf jeden Fall für die beiden Datensätze (Personen/Episoden) für die Bachelorabsolventen (ds3, ds4) bei allen Variablen-jsons der Zugangsweg `download-cuf` herausgenommen werden. Vielleicht können wir uns kurz absprechen, wie man das am besten macht. (Ich würde es einfach per suchen/ersetzen machen?)

**Comment by anneweber** [comment]
@rbirkelbach 
Wir vorhin besprochen, habe ich die variable-jsons jetzt im gra2005-metadata Repo aktualisiert: https://github.com/dzhw/gra2005-metadata/tree/master/data/variables
Es wäre super, wenn Du sie bei der nächsten Gelegenheit ins MDM hochladen und dann das Issue schließen könntest.

Lieben Dank!

**Comment by rbirkelbach** [comment]
done
